services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bscn
      DB_USERNAME: bscn
      DB_PASSWORD: bscn
      APP_URL: http://localhost:8000
    ports:
      - "8000:8000"
      - "5173:5173"
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bscn
      MYSQL_USER: bscn
      MYSQL_PASSWORD: bscn
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devcontainer-db-data:/var/lib/mysql
volumes:
  devcontainer-db-data:
